// Theme
export { ThemeProvider, useTheme, defaultTheme } from './theme/index.ts';
export type { Theme, ThemeColors, ColorVariant, Size } from './theme/index.ts';

// Primitive components
export {
  Box,
  Stack,
  Grid,
  Typography,
  Button,
  IconButton,
  TextField,
  Select,
  Checkbox,
  Switch,
  Chip,
  Badge,
  Avatar,
  Divider,
  Card,
  CardHeader,
  CardContent,
  CardActions,
  Alert,
  CircularProgress,
  LinearProgress,
  Table,
  TableHead,
  TableBody,
  TableRow,
  TableCell,
  List,
  ListItem,
  ListItemText,
  Tabs,
  Tab,
  TabPanel,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Tooltip,
} from './components/primitives/index.ts';

export type {
  BoxProps,
  StackProps,
  GridProps,
  TypographyProps,
  TypographyVariant,
  ButtonProps,
  IconButtonProps,
  TextFieldProps,
  SelectProps,
  SelectOption,
  CheckboxProps,
  SwitchProps,
  ChipProps,
  BadgeProps,
  AvatarProps,
  DividerProps,
  CardProps,
  CardHeaderProps,
  CardContentProps,
  CardActionsProps,
  AlertProps,
  CircularProgressProps,
  LinearProgressProps,
  TableProps,
  TableHeadProps,
  TableBodyProps,
  TableRowProps,
  TableCellProps,
  ListItemProps,
  ListItemTextProps,
  TabsProps,
  TabProps,
  TabPanelProps,
  DialogProps,
  DialogTitleProps,
  DialogContentProps,
  DialogActionsProps,
  TooltipProps,
} from './components/primitives/index.ts';

// Arvist-specific components
export {
  QualityBadge,
  PalletCard,
  DetectionResult,
  MetricCard,
  PluginStatusCard,
  AnnotatedImage,
  CameraView,
  EventFeed,
} from './components/arvist/index.ts';

export type {
  QualityBadgeProps,
  QualityStatus,
  PalletCardProps,
  DetectedProduct,
  DetectionResultProps,
  Detection,
  MetricCardProps,
  PluginStatusCardProps,
  ConnectionStatus,
  AnnotatedImageProps,
  BoundingBox,
  CameraViewProps,
  EventFeedProps,
  MqttEvent,
  EventSeverity,
} from './components/arvist/index.ts';
